<?xml version="1.0" encoding="utf-8"?><Database Name="QL_BanXe" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-ASK17A\SQLEXPRESS;Initial Catalog=QL_BanXe;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_BanXeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ID" Member="IDs">
    <Type Name="ID">
      <Column Name="TaiKhoan" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
</Database>